### ISSUE TITLE
Are the terms `blockSize` and `inlineSize` in the docs backwards?

### ISSUE THREAD

**Issue by tremby** [ZeeCoder/use-resize-observer#104]
In the docs you have, in a table:

> width / undefined | number / The width (or "blockSize") of the element.
> height / undefined | number / The height (or "inlineSize") of the element.

With "left to right then top to bottom" layouts, block is vertical and inline is horizontal, so these seem backwards.

**Comment by ZeeCoder** [comment]
You're right!

Some proof:
- [uRO code](https://github.com/ZeeCoder/use-resize-observer/blob/master/src/index.ts#L118-L119)
- [MDN example](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry#examples)

Fixed in master.
Nice spot, ty! :pray:
