### ISSUE TITLE
Copyright missing from MIT license file

### ISSUE THREAD

**Issue by tvainio** [ZeeCoder/use-resize-observer#18]
Hi,

I just noticed that there's no copyright defined in the LICENSE file. According to  https://opensource.org/licenses/MIT template there should be a line that defines the copyright, something like: `Copyright 2019 Viktor Hubert <rpgmorpheus@gmail.com>`

Please add it to make the license file valid. Thanks!

**Comment by ZeeCoder** [comment]
Good catch, will release in v5 :ok_hand:
