### ISSUE TITLE
Can't pass sizes to parent components

### ISSUE THREAD

**Issue by corysimmons** [ZeeCoder/use-resize-observer#20]
This would be really handy with things like styled-components. I peeked at the source and it looks like it's using useEffect under the hood, so I'm not sure why it isn't able to watch/update appropriately.

https://codesandbox.io/s/useresizeobserver-react-hook-cstgc

**Comment by ZeeCoder** [comment]
You have a missing `px` in your CSS calc, just change it to:
`calc(300px + ${props.h}px)`

**Comment by corysimmons** [comment]
hah, my bad. Thanks Viktor. :)
