### ISSUE TITLE
Support in Safari

### ISSUE THREAD

**Issue by Simply1993** [ZeeCoder/use-resize-observer#30]
Need add polyfill for browsers without ResizeObserver (e.x. Safari).

**Comment by ZeeCoder** [comment]
Please refer to this section in the documentation:
https://github.com/ZeeCoder/use-resize-observer#transpilation--polyfilling

**Comment by Simply1993** [comment]
Did you check it last safari? I've some problem if I use this polyfill

**Comment by ZeeCoder** [comment]
No I didn't, your phrasing made it sound like you didn't try the polyfilled version at all.

Which version of Safari did you try to use it in?
What are the exact problems you are having?

Could you try to polyfill yourself to see if the issue is with the specific polyfill shipped here or not?

**Comment by Simply1993** [comment]
I tried to use polyfill.

Sry, but it's really my fault. My safari was broken :D

Thanks for fast reaction for issue 👍

**Comment by ZeeCoder** [comment]
no worries, glad that it works 👌
