### ISSUE TITLE
No way to set box sizing

### ISSUE THREAD

**Issue by hipstersmoothie** [ZeeCoder/use-resize-observer#41]
# Bug Report

I need to be able to set the box that resize observers uses

## Describe the Bug

Right now I can't get it to respect `box-sizing: border-box`

## How to Reproduce

Try to size an element with `box-sizing: border-box`

## Expected Behavior

Should be able to make it take padding into account

**Comment by ZeeCoder** [comment]
Might be a duplicate of this:
https://github.com/ZeeCoder/use-resize-observer/pull/31

**Comment by hipstersmoothie** [comment]
It is! Feel free to close this
