### ISSUE TITLE
Type definitions for TypeScript

### ISSUE THREAD

**Issue by imran-ebi** [ZeeCoder/use-resize-observer#6]
I am using `use-resize-observer` with TypeScript and noticed there aren't any type definitions for it. It will be great, if it is included with the npm package. I have already created a small definitions file for our project to get it to work with TypeScript. I'll create a pull request with those changes.

**Comment by ZeeCoder** [comment]
Feel free to create a PR, I unfortunately haven't had the chance to look into Typescript yet.

**Comment by imran-ebi** [comment]
I just created it: #7

**Comment by ZeeCoder** [comment]
Deployed as v3.1.0.
Thanks mate 🙌
