### ISSUE TITLE
Dynamic array of elements

### ISSUE THREAD

**Issue by oscarsidebo** [ZeeCoder/use-resize-observer#60]
I'm rendering an array of elements and need to capture the width of each element individually.

This hook works perfectly for a single element but is there a way to capture the sizes of a dynamic amount of elements? 

I saw the example of reusing the hook by passing in custom refs but that example requires you to create all refs up front which wouldn't be possible with a dynamic amount of elements.

Any advice 🙏?

**Comment by ZeeCoder** [comment]
I would compose the hook into a component, because as opposed to hooks, components can be rendered conditionally.
Then I'd map the set of elements to a set of these components, and aggregate the result from their onResize callback.

Hope that helps.

**Comment by oscarsidebo** [comment]
That worked, thanks

**Comment by ZeeCoder** [comment]
👌
