### ISSUE TITLE
SSR HTMLDivElement is not defined in     7.0.0

### ISSUE THREAD

**Issue by DoctorEaker** [ZeeCoder/use-resize-observer#74]
I'm using Nextjs and I noticed that when I use useResizeObserver<HTMLDivElement> in version 7.0.0 it throws the following error:

![image](https://user-images.githubusercontent.com/15178005/122486551-e93fff80-cf9e-11eb-8738-2de235ce2619.png)

But if I use version 6.1.0 it works alright
Haven't checked in other versions

**Comment by ZeeCoder** [comment]
Yeah this is related to https://github.com/ZeeCoder/use-resize-observer/pull/62
Thanks for flagging.
