### ISSUE TITLE
useResizeDetector resize method is not triggering in v7.0.1 

### ISSUE THREAD

**Issue by opr1cob** [ZeeCoder/use-resize-observer#82]
useResizeDetector({
     ref: communicationref,
     onResize: debounce(handlecommunicationResize, delay, { maxWait: 1000 }),
   })

 function handlecommunicationResize({ height }) {
  console.log(height);
  }

its working perfectly in v7.0.0

**Comment by ZeeCoder** [comment]
Interesting.
Can you also post the code for `debounce` and `delay`?

Or better yet, could you create a [codesandbox](https://codesandbox.io/), reproducing the issue?

For the time being, you can also try and use this solution for a debounced hook instead:
https://codesandbox.io/s/use-resize-observer-throttle-and-debounce-8uvsg?file=/src/useDebouncedResizeObserver.js

**Comment by opr1cob** [comment]
without debounce and delay , resize callback is not triggering
useResizeDetector({
ref: communicationref,
onResize: ({ width, height }) => {
   console.log(height);    },
})

**Comment by ZeeCoder** [comment]
That should work for sure, and I have tests covering it.
I really can't look into the issue without having a way to reproduce it.

**Comment by ZeeCoder** [comment]
One thing I'd also try from the top of my head is using the callback ref returned by the hook, instead of passing in an object ref, so:

```tsx
const { ref } = useResizeDetector({
  onResize: ({ width, height }) => {
    console.log(height);
  },
});

<div ref={ref} />
```

This would work better if you mount the observed component with a delay for example.

**Comment by opr1cob** [comment]
I have tried the suggested way to capture the callback but no luck , its not working in v7.0.1

**Comment by ZeeCoder** [comment]
Sorry I really am unable to help unless you provide me a reproduction of the issue through either a repo, codesandbox or something similar.

**Comment by ZeeCoder** [comment]
I'm closing this for now, but feel free to reopen if you have a reproduction.
