### ISSUE TITLE
Using the same ResizeObserver instance for all hooks for better performance

### ISSUE THREAD

**Issue by DanielGiljam** [ZeeCoder/use-resize-observer#84]
Have you considered using the same ResizeObserver for all hooks instead of creating a separate ResizeObserver instance for each hook? Multiple observers each observing one element seems to be less performant than one observer observing multiple elements (see https://github.com/WICG/resize-observer/issues/59#issuecomment-408098151).

**Comment by ZeeCoder** [comment]
Yes, feel free to chip in this discussion:
https://github.com/ZeeCoder/use-resize-observer/discussions/80
