### ISSUE TITLE
Why is it suggested to instal as a dev dependency

### ISSUE THREAD

**Issue by hepiyellow** [ZeeCoder/use-resize-observer#89]
The README states:
```
yarn add use-resize-observer --dev
# or
npm install use-resize-observer --save-dev
```

Isn't it supposed to get built and run in the browser?

**Comment by ZeeCoder** [comment]
That is correct, that's how it's used.
It's all based on your setup: I worked with a lot of setup that had a Node.js backend and a frontend within the same repo, so dependencies were node's, while dev deps were the frontend's.

There's nothing "clever" done here, you do you. :)

**Comment by ZeeCoder** [comment]
Also see the discussion here:
https://github.com/ZeeCoder/use-resize-observer/discussions/87
