### ISSUE TITLE
No values reported when using React StrictMode

### ISSUE THREAD

**Issue by fabianishere** [ZeeCoder/use-resize-observer#90]
Hi, 

I am using this hook in one of my projects in conjunction with React 18 and Strict Mode. However, it appears that the hook does not report any values when used together with React Strict Mode.

See the following [CodeSandbox](https://codesandbox.io/s/4f28on) for a demonstration of this issue.

This issue is caused by the fact that React Strict Mode renders components twice in development mode in order to detect problems. In particular, this behavior causes problems with the following logic (for tracking unmounts):

https://github.com/ZeeCoder/use-resize-observer/blob/653b0b98d5614b083835880736555b79536326aa/src/index.ts#L196-L200

Because the component is rendered twice, the component is marked as unmounted and no further size updates are reported by the hook. 

I believe the following patch should resolve this issue:

```diff
  const didUnmount = useRef(false);
  useEffect(() => {
+   didUnmount.current = false;
    return () => {
      didUnmount.current = true;
    };
  }, []);
```

**Comment by ZeeCoder** [comment]
Thank you for the reproduction and the detailed report. :pray: 
I plan to do a release soon, just have to update the tests so that they run for at least React 17 and 18 to ensure compatibility.

**Comment by fabianishere** [comment]
Awesome, let me know if I can be of any help :)

**Comment by SawasReaper** [comment]
Any update on that one? ^^ 🙏

**Comment by ZeeCoder** [comment]
Hopefully I'll have some time this weekend to wrap things up :crossed_fingers:
