### ISSUE TITLE
export TS types

### ISSUE THREAD

**Issue by holic** [ZeeCoder/use-resize-observer#98]
I have a throttled `onResize` handler. I found that unless I wrap in a `useCallback`, the throttling doesn't take effect because the resize handler triggers a dimension change, which triggers a rerender, which replaces the `onResize` handler with a new one (starting a fresh throttle timer).

However, moving out the `onResize` handler means I lose out on some type inference. I don't love copying over types and would prefer to import them. Looks like this library declares types but doesn't export them, so I can't use them directly.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/508855/202237544-e5fdccd4-b236-40b7-8c16-4bcd73f5fc9b.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/508855/202237324-899d5958-a9e7-4b8c-9971-b3f127243e91.png">

Here's my current workaround:
<img width="879" alt="image" src="https://user-images.githubusercontent.com/508855/202237378-32820c92-4833-485b-a7cc-c75d08a45a74.png">

**Comment by ZeeCoder** [comment]
Yeah I see no reason not to :thinking:

**Comment by ZeeCoder** [comment]
@holic could you check if the above mentioned alpha release addresses this as expected?

**Comment by holic** [comment]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/508855/203139011-f096731a-90a3-48dd-a0b1-5ffd83114c79.png">

Looks great, thank you!

On the original motivation/need for this, is it expected that the resize handler reference (when re-rendering) is not "stable"? Is it expected that we should wrap our `onResize` in a `useCallback` to make it stable? 

<img width="734" alt="image" src="https://user-images.githubusercontent.com/508855/203139259-8507ea56-62eb-48af-a487-ae65b23f4460.png">

(just passing in the `throttle`-wrapped function into `onResize` results in ~nothing being throttled, because the function is recreated each render, which causes `useResizeObserver`'s `useEffect` to reevaluate.

**Comment by ZeeCoder** [comment]
Great!

On throttling, I'm not sure I understand the issue you're facing, can you share a codesandbox by any chance?
Also, is the throttling example in the docs not working for you?
(See here: https://codesandbox.io/s/use-resize-observer-throttle-and-debounce-8uvsg?file=/src/useThrottledResizeObserver.js)

On the callback:
`uRO` always calls the latest `onResize` instance.
But regardless of what the hook does though, in order for a throttle function to work you'd have to have a stable instance, so that it can internally register the individual calls and handle the throttling.

(I'll hold off on releasing until we wrap up this discussion in case there's anything else actionable here.)

**Comment by holic** [comment]
I hadn't seen the example, but it's doing what I ended up with (I just happened to thread it through `useCallback` instead of `useMemo`). A stable instance is what I was wondering about!

All good to go here. Thank you!

**Comment by ZeeCoder** [comment]
Nice, one last question @holic if you had time: did you not find the throttle example in the docs, or did you just not think to check them at all?
I'm just wondering if there's anything I could improve on the docs in your opinion to maybe better surface examples like these?

**Comment by holic** [comment]
I just missed that there was an example for throttling, just went straight to implementing it myself.
